name: deploy Notes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # 可以选择你需要的 Node.js 版本

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run the build command
      - name: Run build
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The branch where you want to deploy your build (usually gh-pages)
          publish_branch: gh-pages
          # The folder where the build output is located (usually `build` for React)
          publish_dir: ./dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
